name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README with GitHub Stats
        run: |
          echo "Updating stats..."
          # Placeholder – GitHub stats is usually shown via shields or vercel deploys
          # If you just want dynamic images in README, no need to rebuild locally

      - name: Commit & Push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: update stats [skip ci]" || echo "no changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
